### ISSUE TITLE
tests failures: Failure/Error: flush_redis Connection timed out

### ISSUE THREAD

**Issue by rngadam** [transist/echidna-streaming#43]
```
$ bundle exec rspec spec/

Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

...........FFFFFF................

Failures:

  1) Keyword keys day_key 
     Failure/Error: flush_redis
     Redis::TimeoutError:
       Connection timed out
     # ./spec/models/keyword_spec.rb:6:in `block (2 levels) in <top (required)>'

  2) Keyword keys month_key 
     Failure/Error: flush_redis
     Redis::TimeoutError:
       Connection timed out
     # ./spec/models/keyword_spec.rb:6:in `block (2 levels) in <top (required)>'

  3) Keyword keys year_key 
     Failure/Error: flush_redis
     Redis::TimeoutError:
       Connection timed out
     # ./spec/models/keyword_spec.rb:6:in `block (2 levels) in <top (required)>'

  4) Keyword keys minute_source_id_key 
     Failure/Error: flush_redis
     Redis::TimeoutError:
       Connection timed out
     # ./spec/models/keyword_spec.rb:6:in `block (2 levels) in <top (required)>'

  5) Keyword keys hour_source_id_key 
     Failure/Error: flush_redis
     Redis::TimeoutError:
       Connection timed out
     # ./spec/models/keyword_spec.rb:6:in `block (2 levels) in <top (required)>'

  6) Keyword keys day_source_id_key 
     Failure/Error: flush_redis
     Redis::TimeoutError:
       Connection timed out
     # ./spec/models/keyword_spec.rb:6:in `block (2 levels) in <top (required)>'
```

**Comment by 0x1b2c** [comment]
I've also got redis timeout error several minutes ago, and noticed redis-server consumes 100% CPU at that moment.

**Comment by flyerhzm** [comment]
Is it reproduceable? flush_redis looks through all of redis keys and remove
them in tests.

On Mon, Apr 15, 2013 at 5:45 PM, Rainux Luo notifications@github.comwrote:

> I've also got redis timeout error several minutes ago, and noticed
> redis-server consumes 100% CPU at that moment.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/transist/echidna-streaming/issues/43#issuecomment-16375792
> .

## 

Best regards,
Richard Huang

http://huangzhimin.com
http://www.huangzhimin.comhttp://rails-bestpractices.com,
http://railsbp.com
https://github.com/flyerhzm http://github.com/flyerhzm,
https://github.com/railsbp
@flyerhzm, @railsbp
